apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-logger
  labels:
    heritage: deis
spec:
  replicas: 1
  selector:
    app: deis-logger
  template:
    metadata:
      labels:
        app: deis-logger
    spec:
      containers:
      - name: deis-logger
        image: quay.io/deis/logger:v2-beta
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
          name: http
        - containerPort: 1514
          name: transport
          protocol: UDP
        env:
        - name: "DRAIN_URL"
          value: "tcp://logs.papertrailapp.com:57926"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8088
          initialDelaySeconds: 1
          timeoutSeconds: 1
